Fixed squished text on save plot images
Ellmen/alcov pull request #3
Opened 2022-05-11 19:28 UTC by JennKnapp

2022-05-11 19:45 UTC, Ellmen requested changes

2022-05-11 19:45 UTC, Ellmen commented on alcov/lineages.py
> -    if img_path is not None:
@JennKnapp this block (and the img_path=None) argument make it so that saving the figures is optional so this shouldn't be deleted

2022-05-11 19:45 UTC, Ellmen commented on alcov/lineages.py
> -def plot_lineages(sample_results, sample_names, img_path=None, all_lins=False):
see below

2022-05-11 19:45 UTC, Ellmen commented on alcov/lineages.py
> +    plt.figure(figsize=(16,9))
it probably makes sense to move this into the `if img_path is not None` section, since we only need to set the size if we are saving it

2022-05-11 20:28 UTC, JennKnapp reviewed
Looks good to me

2022-05-12 21:06 UTC, Ellmen approved these changes

2022-05-12 21:07 UTC, merged

2022-05-12 21:07 UTC, Ellmen commented
Thanks!